use super::{
    alternate_headwords::AlternateHeadwords,
    artwork::Artwork,
    cognate_cross_references::CognateCrossReferences,
    defined_run_ons::DefinedRunOns,
    directional_cross_reference_section::DirectionalCrossReferenceSection,
    etymology::Etymology,
    first_known_use::FirstKnownUse,
    headword_information::HeadwordInformation,
    homograph::Homograph,
    inflections::Inflections,
    labels::{FunctionalLabel, GeneralLabels},
    meta::EntryMetadata,
    quotation_section::QuotationSection,
    sense::definition_section::DefinitionSections,
    short_definitions::ShortDefinitions,
    synonym_section::SynonymSection,
    tables::Table,
    undefined_run_ons::UndefinedRunOns,
    usage_section::UsageSection,
    variants::Variants,
};

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Entry {
    pub meta: EntryMetadata,
    pub hwi: HeadwordInformation,
    pub hom: Option<Homograph>,
    pub ahws: Option<AlternateHeadwords>,
    pub vrs: Option<Variants>,
    pub fl: Option<FunctionalLabel>,
    pub lbs: Option<GeneralLabels>,
    pub ins: Option<Inflections>,
    pub cxs: Option<CognateCrossReferences>,
    pub def: Option<DefinitionSections>,
    pub uros: Option<UndefinedRunOns>,
    pub dros: Option<DefinedRunOns>,
    pub et: Option<Etymology>,
    pub dxnls: Option<DirectionalCrossReferenceSection>,
    pub usages: Option<UsageSection>,
    pub syns: Option<SynonymSection>,
    pub quotes: Option<QuotationSection>,
    pub art: Option<Artwork>,
    pub table: Option<Table>,
    pub date: Option<FirstKnownUse>,
    pub shortdef: Option<ShortDefinitions>,
}
